accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "CC0-1.0",
    "BSD-3-Clause",
    "MPL-2.0",
    "ISC",
    "OpenSSL",
    "Unicode-DFS-2016",
    # The xcm-transactor needs this because of the polkadot dependencies.
    "GPL-3.0"
]
ignore-dev-dependencies = true
ignore-build-dependencies = true
workarounds = [
    "ring",
]
