name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --release
  build-skip-ias-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build with --features skip-ias-check
        run: cargo build --release --features skip-ias-check
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: test
        run: cargo test --all --features runtime-benchmarks
  test-skip-ias-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: test
        run: cargo test --all --features skip-ias-check